apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivebox
  template:
    metadata:
      labels:
        app: hivebox
    spec:
      containers:
      - name: hivebox
        image: docker.io/library/hivebox:0.0.1    
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
